export type StaticSubCounty = { id: number; county_id: number; name: string };

export const STATIC_SUB_COUNTIES: StaticSubCounty[] = [
  // Mombasa (1)
  { id: 1, county_id: 1, name: "Changamwe" },
  { id: 2, county_id: 1, name: "Jomvu" },
  { id: 3, county_id: 1, name: "Kisauni" },
  { id: 4, county_id: 1, name: "Nyali" },
  { id: 5, county_id: 1, name: "Likoni" },
  { id: 6, county_id: 1, name: "Mvita" },
  // Kwale (2)
  { id: 7, county_id: 2, name: "Msambweni" },
  { id: 8, county_id: 2, name: "Lungalunga" },
  { id: 9, county_id: 2, name: "Matuga" },
  { id: 10, county_id: 2, name: "Kinango" },
  // Kilifi (3)
  { id: 11, county_id: 3, name: "Kilifi North" },
  { id: 12, county_id: 3, name: "Kilifi South" },
  { id: 13, county_id: 3, name: "Kaloleni" },
  { id: 14, county_id: 3, name: "Rabai" },
  { id: 15, county_id: 3, name: "Ganze" },
  { id: 16, county_id: 3, name: "Malindi" },
  { id: 17, county_id: 3, name: "Magarini" },
  // Tana River (4)
  { id: 18, county_id: 4, name: "Garsen" },
  { id: 19, county_id: 4, name: "Galole" },
  { id: 20, county_id: 4, name: "Bura" },
  // Lamu (5)
  { id: 21, county_id: 5, name: "Lamu East" },
  { id: 22, county_id: 5, name: "Lamu West" },
  // Taita Taveta (6)
  { id: 23, county_id: 6, name: "Taveta" },
  { id: 24, county_id: 6, name: "Wundanyi" },
  { id: 25, county_id: 6, name: "Mwatate" },
  { id: 26, county_id: 6, name: "Voi" },
  // Garissa (7)
  { id: 27, county_id: 7, name: "Garissa Township" },
  { id: 28, county_id: 7, name: "Balambala" },
  { id: 29, county_id: 7, name: "Lagdera" },
  { id: 30, county_id: 7, name: "Dadaab" },
  { id: 31, county_id: 7, name: "Fafi" },
  { id: 32, county_id: 7, name: "Ijara" },
  // Wajir (8)
  { id: 33, county_id: 8, name: "Wajir North" },
  { id: 34, county_id: 8, name: "Wajir East" },
  { id: 35, county_id: 8, name: "Tarbaj" },
  { id: 36, county_id: 8, name: "Wajir West" },
  { id: 37, county_id: 8, name: "Eldas" },
  { id: 38, county_id: 8, name: "Wajir South" },
  // Mandera (9)
  { id: 39, county_id: 9, name: "Mandera East" },
  { id: 40, county_id: 9, name: "Banissa" },
  { id: 41, county_id: 9, name: "Mandera North" },
  { id: 42, county_id: 9, name: "Mandera South" },
  { id: 43, county_id: 9, name: "Mandera West" },
  { id: 44, county_id: 9, name: "Lafey" },
  // Marsabit (10)
  { id: 45, county_id: 10, name: "Moyale" },
  { id: 46, county_id: 10, name: "North Horr" },
  { id: 47, county_id: 10, name: "Saku" },
  { id: 48, county_id: 10, name: "Laisamis" },
  // Isiolo (11)
  { id: 49, county_id: 11, name: "Isiolo North" },
  { id: 50, county_id: 11, name: "Isiolo South" },
  // Meru (12)
  { id: 51, county_id: 12, name: "Igembe South" },
  { id: 52, county_id: 12, name: "Igembe Central" },
  { id: 53, county_id: 12, name: "Igembe North" },
  { id: 54, county_id: 12, name: "Tigania West" },
  { id: 55, county_id: 12, name: "Tigania East" },
  { id: 56, county_id: 12, name: "North Imenti" },
  { id: 57, county_id: 12, name: "Buuri" },
  { id: 58, county_id: 12, name: "Central Imenti" },
  { id: 59, county_id: 12, name: "South Imenti" },
  // Tharaka Nithi (13)
  { id: 60, county_id: 13, name: "Maara" },
  { id: 61, county_id: 13, name: "Chuka/Igambang'ombe" },
  { id: 62, county_id: 13, name: "Tharaka" },
  // Embu (14)
  { id: 63, county_id: 14, name: "Manyatta" },
  { id: 64, county_id: 14, name: "Runyenjes" },
  { id: 65, county_id: 14, name: "Mbeere South" },
  { id: 66, county_id: 14, name: "Mbeere North" },
  // Kitui (15)
  { id: 67, county_id: 15, name: "Mwingi North" },
  { id: 68, county_id: 15, name: "Mwingi West" },
  { id: 69, county_id: 15, name: "Mwingi Central" },
  { id: 70, county_id: 15, name: "Kitui West" },
  { id: 71, county_id: 15, name: "Kitui Rural" },
  { id: 72, county_id: 15, name: "Kitui Central" },
  { id: 73, county_id: 15, name: "Kitui East" },
  { id: 74, county_id: 15, name: "Kitui South" },
  // Machakos (16)
  { id: 75, county_id: 16, name: "Masinga" },
  { id: 76, county_id: 16, name: "Yatta" },
  { id: 77, county_id: 16, name: "Kangundo" },
  { id: 78, county_id: 16, name: "Matungulu" },
  { id: 79, county_id: 16, name: "Kathiani" },
  { id: 80, county_id: 16, name: "Mavoko" },
  { id: 81, county_id: 16, name: "Machakos Town" },
  { id: 82, county_id: 16, name: "Mwala" },
  // Makueni (17)
  { id: 83, county_id: 17, name: "Mbooni" },
  { id: 84, county_id: 17, name: "Kilome" },
  { id: 85, county_id: 17, name: "Kaiti" },
  { id: 86, county_id: 17, name: "Makueni" },
  { id: 87, county_id: 17, name: "Kibwezi West" },
  { id: 88, county_id: 17, name: "Kibwezi East" },
  // Nyandarua (18)
  { id: 89, county_id: 18, name: "Kinangop" },
  { id: 90, county_id: 18, name: "Kipipiri" },
  { id: 91, county_id: 18, name: "Ol Kalou" },
  { id: 92, county_id: 18, name: "Ol Jorok" },
  { id: 93, county_id: 18, name: "Ndaragwa" },
  // Nyeri (19)
  { id: 94, county_id: 19, name: "Tetu" },
  { id: 95, county_id: 19, name: "Kieni" },
  { id: 96, county_id: 19, name: "Mathira" },
  { id: 97, county_id: 19, name: "Othaya" },
  { id: 98, county_id: 19, name: "Mukurweini" },
  { id: 99, county_id: 19, name: "Nyeri Town" },
  // Kirinyaga (20)
  { id: 100, county_id: 20, name: "Mwea" },
  { id: 101, county_id: 20, name: "Gichugu" },
  { id: 102, county_id: 20, name: "Ndia" },
  { id: 103, county_id: 20, name: "Kirinyaga Central" },
  // Murang'a (21)
  { id: 104, county_id: 21, name: "Kangema" },
  { id: 105, county_id: 21, name: "Mathioya" },
  { id: 106, county_id: 21, name: "Kiharu" },
  { id: 107, county_id: 21, name: "Kigumo" },
  { id: 108, county_id: 21, name: "Maragwa" },
  { id: 109, county_id: 21, name: "Kandara" },
  { id: 110, county_id: 21, name: "Gatanga" },
  // Kiambu (22)
  { id: 111, county_id: 22, name: "Gatundu South" },
  { id: 112, county_id: 22, name: "Gatundu North" },
  { id: 113, county_id: 22, name: "Juja" },
  { id: 114, county_id: 22, name: "Thika Town" },
  { id: 115, county_id: 22, name: "Ruiru" },
  { id: 116, county_id: 22, name: "Githunguri" },
  { id: 117, county_id: 22, name: "Kiambu" },
  { id: 118, county_id: 22, name: "Kiambaa" },
  { id: 119, county_id: 22, name: "Kabete" },
  { id: 120, county_id: 22, name: "Kikuyu" },
  { id: 121, county_id: 22, name: "Limuru" },
  { id: 122, county_id: 22, name: "Lari" },
  // Turkana (23)
  { id: 123, county_id: 23, name: "Turkana North" },
  { id: 124, county_id: 23, name: "Turkana West" },
  { id: 125, county_id: 23, name: "Turkana Central" },
  { id: 126, county_id: 23, name: "Loima" },
  { id: 127, county_id: 23, name: "Turkana South" },
  { id: 128, county_id: 23, name: "Turkana East" },
  // West Pokot (24)
  { id: 129, county_id: 24, name: "Kapenguria" },
  { id: 130, county_id: 24, name: "Sigor" },
  { id: 131, county_id: 24, name: "Kacheliba" },
  { id: 132, county_id: 24, name: "Pokot South" },
  // Samburu (25)
  { id: 133, county_id: 25, name: "Samburu West" },
  { id: 134, county_id: 25, name: "Samburu North" },
  { id: 135, county_id: 25, name: "Samburu East" },
  // Trans Nzoia (26)
  { id: 136, county_id: 26, name: "Kwanza" },
  { id: 137, county_id: 26, name: "Endebess" },
  { id: 138, county_id: 26, name: "Saboti" },
  { id: 139, county_id: 26, name: "Kiminini" },
  { id: 140, county_id: 26, name: "Cherangany" },
  // Uasin Gishu (27)
  { id: 141, county_id: 27, name: "Soy" },
  { id: 142, county_id: 27, name: "Turbo" },
  { id: 143, county_id: 27, name: "Moiben" },
  { id: 144, county_id: 27, name: "Ainabkoi" },
  { id: 145, county_id: 27, name: "Kapseret" },
  { id: 146, county_id: 27, name: "Kesses" },
  // Elgeyo Marakwet (28)
  { id: 147, county_id: 28, name: "Marakwet East" },
  { id: 148, county_id: 28, name: "Marakwet West" },
  { id: 149, county_id: 28, name: "Keiyo North" },
  { id: 150, county_id: 28, name: "Keiyo South" },
  // Nandi (29)
  { id: 151, county_id: 29, name: "Tinderet" },
  { id: 152, county_id: 29, name: "Aldai" },
  { id: 153, county_id: 29, name: "Nandi Hills" },
  { id: 154, county_id: 29, name: "Chesumei" },
  { id: 155, county_id: 29, name: "Emgwen" },
  { id: 156, county_id: 29, name: "Mosop" },
  // Baringo (30)
  { id: 157, county_id: 30, name: "Tiaty" },
  { id: 158, county_id: 30, name: "Baringo North" },
  { id: 159, county_id: 30, name: "Baringo Central" },
  { id: 160, county_id: 30, name: "Baringo South" },
  { id: 161, county_id: 30, name: "Eldama Ravine" },
  { id: 162, county_id: 30, name: "Mogotio" },
  // Laikipia (31)
  { id: 163, county_id: 31, name: "Laikipia West" },
  { id: 164, county_id: 31, name: "Laikipia East" },
  { id: 165, county_id: 31, name: "Laikipia North" },
  // Nakuru (32)
  { id: 166, county_id: 32, name: "Molo" },
  { id: 167, county_id: 32, name: "Njoro" },
  { id: 168, county_id: 32, name: "Naivasha" },
  { id: 169, county_id: 32, name: "Gilgil" },
  { id: 170, county_id: 32, name: "Kuresoi South" },
  { id: 171, county_id: 32, name: "Kuresoi North" },
  { id: 172, county_id: 32, name: "Subukia" },
  { id: 173, county_id: 32, name: "Rongai" },
  { id: 174, county_id: 32, name: "Bahati" },
  { id: 175, county_id: 32, name: "Nakuru Town West" },
  { id: 176, county_id: 32, name: "Nakuru Town East" },
  // Narok (33)
  { id: 177, county_id: 33, name: "Kilgoris" },
  { id: 178, county_id: 33, name: "Emurua Dikirr" },
  { id: 179, county_id: 33, name: "Narok North" },
  { id: 180, county_id: 33, name: "Narok East" },
  { id: 181, county_id: 33, name: "Narok South" },
  { id: 182, county_id: 33, name: "Narok West" },
  // Kajiado (34)
  { id: 183, county_id: 34, name: "Kajiado North" },
  { id: 184, county_id: 34, name: "Kajiado Central" },
  { id: 185, county_id: 34, name: "Kajiado East" },
  { id: 186, county_id: 34, name: "Kajiado West" },
  { id: 187, county_id: 34, name: "Kajiado South" },
  // Kericho (35)
  { id: 188, county_id: 35, name: "Kipkelion East" },
  { id: 189, county_id: 35, name: "Kipkelion West" },
  { id: 190, county_id: 35, name: "Ainamoi" },
  { id: 191, county_id: 35, name: "Bureti" },
  { id: 192, county_id: 35, name: "Belgut" },
  { id: 193, county_id: 35, name: "Sigowet/Soin" },
  // Bomet (36)
  { id: 194, county_id: 36, name: "Sotik" },
  { id: 195, county_id: 36, name: "Chepalungu" },
  { id: 196, county_id: 36, name: "Bomet East" },
  { id: 197, county_id: 36, name: "Bomet Central" },
  { id: 198, county_id: 36, name: "Konoin" },
  // Kakamega (37)
  { id: 199, county_id: 37, name: "Lugari" },
  { id: 200, county_id: 37, name: "Likuyani" },
  { id: 201, county_id: 37, name: "Malava" },
  { id: 202, county_id: 37, name: "Lurambi" },
  { id: 203, county_id: 37, name: "Navakholo" },
  { id: 204, county_id: 37, name: "Mumias West" },
  { id: 205, county_id: 37, name: "Mumias East" },
  { id: 206, county_id: 37, name: "Matungu" },
  { id: 207, county_id: 37, name: "Butere" },
  { id: 208, county_id: 37, name: "Khwisero" },
  { id: 209, county_id: 37, name: "Shinyalu" },
  { id: 210, county_id: 37, name: "Ikolomani" },
  // Vihiga (38)
  { id: 211, county_id: 38, name: "Vihiga" },
  { id: 212, county_id: 38, name: "Sabatia" },
  { id: 213, county_id: 38, name: "Hamisi" },
  { id: 214, county_id: 38, name: "Luanda" },
  { id: 215, county_id: 38, name: "Emuhaya" },
  // Bungoma (39)
  { id: 216, county_id: 39, name: "Mt Elgon" },
  { id: 217, county_id: 39, name: "Sirisia" },
  { id: 218, county_id: 39, name: "Kabuchai" },
  { id: 219, county_id: 39, name: "Bumula" },
  { id: 220, county_id: 39, name: "Kanduyi" },
  { id: 221, county_id: 39, name: "Webuye East" },
  { id: 222, county_id: 39, name: "Webuye West" },
  { id: 223, county_id: 39, name: "Kimilili" },
  { id: 224, county_id: 39, name: "Tongaren" },
  // Busia (40)
  { id: 225, county_id: 40, name: "Teso North" },
  { id: 226, county_id: 40, name: "Teso South" },
  { id: 227, county_id: 40, name: "Nambale" },
  { id: 228, county_id: 40, name: "Matayos" },
  { id: 229, county_id: 40, name: "Butula" },
  { id: 230, county_id: 40, name: "Funyula" },
  { id: 231, county_id: 40, name: "Budalangi" },
  // Siaya (41)
  { id: 232, county_id: 41, name: "Ugenya" },
  { id: 233, county_id: 41, name: "Ugunja" },
  { id: 234, county_id: 41, name: "Alego Usonga" },
  { id: 235, county_id: 41, name: "Gem" },
  { id: 236, county_id: 41, name: "Bondo" },
  { id: 237, county_id: 41, name: "Rarieda" },
  // Kisumu (42)
  { id: 238, county_id: 42, name: "Kisumu East" },
  { id: 239, county_id: 42, name: "Kisumu West" },
  { id: 240, county_id: 42, name: "Kisumu Central" },
  { id: 241, county_id: 42, name: "Seme" },
  { id: 242, county_id: 42, name: "Nyando" },
  { id: 243, county_id: 42, name: "Muhoroni" },
  { id: 244, county_id: 42, name: "Nyakach" },
  // Homa Bay (43)
  { id: 245, county_id: 43, name: "Kasipul" },
  { id: 246, county_id: 43, name: "Kabondo Kasipul" },
  { id: 247, county_id: 43, name: "Karachuonyo" },
  { id: 248, county_id: 43, name: "Rangwe" },
  { id: 249, county_id: 43, name: "Homa Bay Town" },
  { id: 250, county_id: 43, name: "Ndhiwa" },
  { id: 251, county_id: 43, name: "Mbita" },
  { id: 252, county_id: 43, name: "Suba" },
  // Migori (44)
  { id: 253, county_id: 44, name: "Rongo" },
  { id: 254, county_id: 44, name: "Awendo" },
  { id: 255, county_id: 44, name: "Suna East" },
  { id: 256, county_id: 44, name: "Suna West" },
  { id: 257, county_id: 44, name: "Uriri" },
  { id: 258, county_id: 44, name: "Nyatike" },
  { id: 259, county_id: 44, name: "Kuria West" },
  { id: 260, county_id: 44, name: "Kuria East" },
  // Kisii (45)
  { id: 261, county_id: 45, name: "Bonchari" },
  { id: 262, county_id: 45, name: "South Mugirango" },
  { id: 263, county_id: 45, name: "Bomachoge Borabu" },
  { id: 264, county_id: 45, name: "Bobasi" },
  { id: 265, county_id: 45, name: "Bomachoge Chache" },
  { id: 266, county_id: 45, name: "Nyaribari Masaba" },
  { id: 267, county_id: 45, name: "Nyaribari Chache" },
  { id: 268, county_id: 45, name: "Kitutu Chache North" },
  { id: 269, county_id: 45, name: "Kitutu Chache South" },
  // Nyamira (46)
  { id: 270, county_id: 46, name: "Kitutu Masaba" },
  { id: 271, county_id: 46, name: "West Mugirango" },
  { id: 272, county_id: 46, name: "North Mugirango" },
  { id: 273, county_id: 46, name: "Bomet South" },
  // Nairobi (47)
  { id: 274, county_id: 47, name: "Westlands" },
  { id: 275, county_id: 47, name: "Dagoretti North" },
  { id: 276, county_id: 47, name: "Dagoretti South" },
  { id: 277, county_id: 47, name: "Langata" },
  { id: 278, county_id: 47, name: "Kibra" },
  { id: 279, county_id: 47, name: "Roysambu" },
  { id: 280, county_id: 47, name: "Kasarani" },
  { id: 281, county_id: 47, name: "Ruaraka" },
  { id: 282, county_id: 47, name: "Embakasi South" },
  { id: 283, county_id: 47, name: "Embakasi North" },
  { id: 284, county_id: 47, name: "Embakasi Central" },
  { id: 285, county_id: 47, name: "Embakasi East" },
  { id: 286, county_id: 47, name: "Embakasi West" },
  { id: 287, county_id: 47, name: "Makadara" },
  { id: 288, county_id: 47, name: "Kamukunji" },
  { id: 289, county_id: 47, name: "Starehe" },
  { id: 290, county_id: 47, name: "Mathare" },
];
